### ISSUE TITLE
npm run build  构建报错!

### ISSUE THREAD

**Issue by hqzxjczx** [yaoyao1987/vue-cli-multipage#10]
在  webpack.prod.conf.js 文件里, 最后导出 module.exports = webpackConfig,
而在此之前却已经调用    module.exports.plugins.push(new HtmlWebpackPlugin(conf)),

故解决防范 可以 去掉  module.exports = webpackConfig,
.... 在 var  webpackConfig = merge(baseWebpackConfig, {

改为   module.exports = merge(baseWebpackConfig, {

**Comment by yaoyao1987** [comment]
已修改，谢谢
