### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by yanlee26** [yaoyao1987/vue-cli-multipage#13]
你好，我照你说的做；怎么页面没显示，哪点信息配置错了。。。
webpack: wait until bundle finished: /index.html
webpack: wait until bundle finished: /favicon.ico
webpack built 1671c54f98ff6da2bbe6 in 6673ms
Hash: 1671c54f98ff6da2bbe6
Version: webpack 1.13.3
Time: 6673ms
            Asset       Size  Chunks             Chunk Names
  module/index.js    1.03 MB       0  [emitted]  module/index
   module/info.js     897 kB       1  [emitted]  module/info
module/index.html  558 bytes          [emitted]
 module/info.html  306 bytes          [emitted]
Child html-webpack-plugin for "module\index.html":
                Asset     Size  Chunks       Chunk Names
    module/index.html  1.47 MB       0
Child html-webpack-plugin for "module\info.html":
               Asset     Size  Chunks       Chunk Names
    module/info.html  1.47 MB       0
webpack: bundle is now VALID.

**Comment by yaoyao1987** [comment]
@yanlee26 ,webpack.dev.conf.js中有版本冲突，不确定你是不是因为这个原因

**Comment by yanlee26** [comment]
maybe,I am a freshman in field of webpack...

**Comment by yaoyao1987** [comment]
@yanlee26 ，你可以看下滴滴公共前端团队的这篇文章https://gold.xitu.io/post/584e48b2ac502e006c74a120
详细讲解了vue-cli webpack 配置

**Comment by yanlee26** [comment]
好的，谢啦
