### ISSUE TITLE
我只要加入第三方组件库就会报错，不知道怎么回事

### ISSUE THREAD

**Issue by busyhe** [yaoyao1987/vue-cli-multipage#15]
bootstrap bb8c77f…:50Uncaught TypeError: Cannot read property 'call' of undefined

**Comment by yaoyao1987** [comment]
@BusyHe ，你是怎么引入第三方库的？？贴下代码看一下

**Comment by busyhe** [comment]
解决了，webpack配置的问题，在webapck issues上找到了解决方法，
```
new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      chunks: ['vendor']
    })
```
把这行代码删了，
然后就正常了
