### ISSUE TITLE
在vue组件里使用saas会报错

### ISSUE THREAD

**Issue by FisherWu29** [yaoyao1987/vue-cli-multipage#17]
<style lang='scss'>
$colorFe:#ff6633
#list {
    display: flex;
    color:$colorFe
}
#pre{
  transform: translate(0,0);
}
</style>
报错：
 Invalid CSS after "#list": expected 1 selector or at-rule, was "{"
 in D:\vue-cli-multipage-master\src\module\index\list.vue (line 17, col

**Comment by yaoyao1987** [comment]
@wufuxi ，你需要安装node-sass、sass-loader，才能使用sass
