### ISSUE TITLE
var glob = require('glob');的疑问

### ISSUE THREAD

**Issue by zhy6421867** [yaoyao1987/vue-cli-multipage#5]
package.json里面并没有对应的依赖声明,想问"glob"是从哪里来的.

**Comment by yaoyao1987** [comment]
@zhy6421867 ，这里的glob是nodejs的glob模块，是用来读取webpack入口目录文件的

**Comment by zhy6421867** [comment]
我node版本4.4.7 npm版本2.15.8.
是不是版本的问题?

**Comment by yaoyao1987** [comment]
@zhy6421867 ，版本的问题，你指的是什么，好像没有具体的问题

**Comment by zhy6421867** [comment]
我的意思是:是不是我node和npm的版本低了,没有glob模块
